# -*- coding: utf-8 -*-
"""ScoreLaship_Telegram_Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbA8kGtSZblgg8Zcfixly9gltrtufGiN
"""

# ========================
# Install dependencies
# ========================
!pip install pyTelegramBotAPI schedule pytz --quiet

# ========================
# Import libraries
# ========================
import telebot
import schedule
import time
import pytz
import threading

# ========================
# Bot configuration
# ========================
BOT_TOKEN = "7694107871:AAGm6Uxr3-GqHRF7hqog_8Ucvn-1DI-7jwc"   # Replace with your real token
CHAT_ID = 6444120693                     # Your group ID

bot = telebot.TeleBot(BOT_TOKEN)

# ========================
# Footer message for all posts
# ========================
FOOTER = """
🌐 *Share to your friends*

Join our community 👉 [Click Here](https://chat.whatsapp.com/LwPfFoi2T2O6oXuRXpoZfd?mode=wwt)
"""

# ========================
# Scholarship messages
# ========================
def nigeria_scholarship():
    message = f"""🇳🇬 *Nigerian Scholarship Update:*

*One Youth Young Leaders Scholarship 2025 for Undergraduates: Fully Funded Opportunity*

*Benefits:*
• Full Scholarship worth ₦1m
• Tuition
• Living Stipends

*Requirements:*
• Must be a student of any public university in Nigeria
• Must have not less than 4.5 CGPA

*Deadline:* November 30, 2025

[Apply Here](https://docs.google.com/forms/d/1UpUO6-q9bOJ8F6Qdjk00i7iRymK16047x6pui0oJrsM/viewform)
{FOOTER}
"""
    bot.send_message(CHAT_ID, message, parse_mode="Markdown")

def international_scholarship():
    message = f"""🌍 *International Scholarship Update:*

*Global Future Leaders Scholarship 2025 (Fully Funded)*

*Benefits:*
• Full tuition
• Monthly stipend
• Visa & flight support

*Deadline:* November 30, 2025

[Apply Here](https://example.com/apply)
{FOOTER}
"""
    bot.send_message(CHAT_ID, message, parse_mode="Markdown")

# ========================
# Manual commands
# ========================
@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.send_message(
        message.chat.id,
        "👋 Hello! I’m ScoreLaship Hub AI. I will post Nigerian scholarships every morning and International ones every evening automatically in this group."
    )

@bot.message_handler(commands=['nigeria'])
def manual_nigeria(message):
    nigeria_scholarship()

@bot.message_handler(commands=['international'])
def manual_international(message):
    international_scholarship()

# ========================
# Scheduler for automatic posts
# ========================
tz = pytz.timezone("Africa/Lagos")

# Schedule posts
schedule.every().day.at("10:40").do(nigeria_scholarship)      # Nigerian scholarships
schedule.every().day.at("19:40").do(international_scholarship) # International scholarships

def run_scheduler():
    while True:
        schedule.run_pending()
        time.sleep(60)

# Run scheduler in a separate thread
threading.Thread(target=run_scheduler).start()

# ========================
# Start bot polling
# ========================
print("🤖 ScoreLaship Hub AI is now active and posting automatically!")
bot.infinity_polling()

# ========================
# Install dependencies
# ========================
!pip install pyTelegramBotAPI schedule pytz --quiet

# ========================
# Imports
# ========================
import telebot
import schedule
import time
import pytz
import threading
from datetime import datetime

# ========================
# Bot config
# ========================
BOT_TOKEN = "7694107871:AAGm6Uxr3-GqHRF7hqog_8Ucvn-1DI-7jwc"   # Replace with your bot token
CHAT_ID = 6444120693                     # Replace with your group chat ID

bot = telebot.TeleBot(BOT_TOKEN)

# ========================
# Footer for all posts
# ========================
FOOTER = """
🌐 *Share to your friends*

Join our community 👉 [Click Here](https://chat.whatsapp.com/LwPfFoi2T2O6oXuRXpoZfd?mode=wwt)
"""

# ========================
# Scholarship lists (example)
# ========================
nigeria_scholarships = [
    {
        "title": "One Youth Young Leaders Scholarship 2025",
        "link": "https://docs.google.com/forms/d/1UpUO6-q9bOJ8F6Qdjk00i7iRymK16047x6pui0oJrsM/viewform",
        "deadline": "2025-11-30",
        "eligibility": "Nigeria",
        "description": "Fully funded opportunity for Nigerian undergraduates"
    },
    # Add more Nigerian scholarships here
]

tech_opportunities = [
    {
        "title": "Free Tech Workshop 2025",
        "link": "https://example.com/tech",
        "deadline": "2025-12-15",
        "eligibility": "Open",
        "description": "Free coding and tech skill workshops"
    },
    # Add more tech opportunities here
]

international_scholarships = [
    {
        "title": "DAAD 2025 Scholarship",
        "link": "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
        "deadline": "2025-12-31",
        "eligibility": "Nigerians eligible",
        "description": "Fully funded Masters and PhD scholarships"
    },
    # Add more international scholarships here
]

# ========================
# Index trackers to avoid repetition
# ========================
indexes = {
    "nigeria": 0,
    "tech": 0,
    "international": 0
}

# ========================
# Helper to check if scholarship is still ongoing
# ========================
def is_ongoing(deadline_str):
    try:
        deadline = datetime.strptime(deadline_str, "%Y-%m-%d")
        today = datetime.now(pytz.timezone("Africa/Lagos")).date()
        return today <= deadline.date()
    except:
        return False

# ========================
# Functions to post scholarships
# ========================
def post_scholarship(category_list, category_name):
    global indexes
    if len(category_list) == 0:
        return

    idx = indexes[category_name] % len(category_list)
    scholarship = category_list[idx]

    if not is_ongoing(scholarship["deadline"]):
        # Skip expired, move to next
        indexes[category_name] += 1
        return

    message = f"""🎓 *{scholarship['title']}*\n\n{scholarship['description']}\n\n*Deadline:* {scholarship['deadline']}\n*Eligibility:* {scholarship['eligibility']}\n\n[Apply Here]({scholarship['link']})\n{FOOTER}"""
    bot.send_message(CHAT_ID, message, parse_mode="Markdown")
    indexes[category_name] += 1

# ========================
# Scheduled post functions
# ========================
def post_nigeria():
    post_scholarship(nigeria_scholarships, "nigeria")

def post_tech():
    post_scholarship(tech_opportunities, "tech")

def post_international():
    post_scholarship(international_scholarships, "international")

# ========================
# Manual commands
# ========================
@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.send_message(message.chat.id, "👋 Hello! I will automatically post Nigerian scholarships at 8:30 AM, Free Tech Opportunities at 1:30 PM, and International scholarships at 8:30 PM daily in this group.")

@bot.message_handler(commands=['nigeria'])
def manual_nigeria(message):
    post_nigeria()

@bot.message_handler(commands=['tech'])
def manual_tech(message):
    post_tech()

@bot.message_handler(commands=['international'])
def manual_international(message):
    post_international()

# ========================
# Scheduler
# ========================
tz = pytz.timezone("Africa/Lagos")

schedule.every().day.at("08:30").do(post_nigeria)
schedule.every().day.at("13:30").do(post_tech)
schedule.every().day.at("20:30").do(post_international)

def run_scheduler():
    while True:
        schedule.run_pending()
        time.sleep(60)

# ========================
# Run scheduler in a thread
# ========================
threading.Thread(target=run_scheduler).start()

# ========================
# Start bot
# ========================
print("🤖 ScoreLaship Hub AI is now active and posting automatically!")
bot.infinity_polling()